- README.md
- package-lock.json
- package.json
- source/example.js
- tests/example.test.js
- Updated instructions
- Set up Jest to test
- Added scripts to run lint and test
- Test run for the github action as well : )
> jest bring up

- source/assets/scripts/api.js
added function to deal with data
> api function added

- .github/workflows/jsdoc.yml
Added Jsdoc action
Followed instructions [here](https://github.com/marketplace/actions/jsdoc-action)
If you use vscode, all you have to do is type in `/**` and the editor will generate a template for you : )
> add jsdoc action

- source/assets/scripts/foodie.js
- source/assets/styles/foodie.css
Update prev and next buttons so that they display properly based on which step we're at
Add or remove the hidden class from buttons when appropriate
> update prev, next buttons

- tests/e2e/recipe-detailE2E.test.js
#41
Add recipe detail page test (E2E test)
Two TODOs should be done after the add page & search page are implemented.
> Add recipe detail page test

- source/assets/scripts/index.js
- source/assets/scripts/recipe-add.js
- source/assets/scripts/recipe-detail.js
- source/assets/scripts/recipe-searchPage.js
- source/assets/scripts/setting.js
> Added AddRecipe to Nav Bar

- .github/workflows/codacy-analysis.yml
Integrate the Codacy GitHub Action with GitHub code scanning to display the analysis results in repo under the tab Security, page Code scanning alerts.
update codacy-analysis.yml to include additional features and tasks for CI/CD pipeline
All analysis made by Codacy should be available under **Security/page Code scanning alerts**
> update codacy include Github code scanning

- source/assets/styles/index.css
- source/assets/styles/recipe-add.css
- source/assets/styles/recipe-searchPage.css
- source/assets/styles/setting.css
Fixed navbar on each pages
revise the section box in the css file
small update no need further instruction
> navbar Fixed

- source/assets/scripts/recipe-detail.js
Recipe detail page documentation
Recipe detail page documentation
module: recipe-detail
> Recipe detail page documentation

- source/assets/styles/foodie.css
- source/assets/styles/index.css
- source/assets/styles/preference-setting.css
- source/assets/styles/recipe-add.css
- source/assets/styles/recipe-detail.css
- source/assets/styles/recipe-searchPage.css
- source/assets/styles/setting.css
- source/settings.html
fixed the #74 now all the pages show the last button and l left 30px more from the last buttons to the navbar
add margin-bottom to the last section
small update, no instruction
> navbar fixed all pages and resolve the problem: not showing the buttons

- tests/e2e/exampleE2E.test.js
- tests/e2e/settings.test.js
close #62 
close #61 
Add some tests for nav and searchPage
> Add some tests for nav and searchPage

- source/assets/scripts/api.js
- tests/unit/api.test.js
add some test and set intolerance function. Intolerance function will receive an array of intolerance the put them in the local storage with key 'intolerance'. Every time it gets called it will replace the set.
> Intolerance add

- tests/e2e/recipe-detailE2E.test.js
Add tests for recipe detail page
Check click go add
> Recipe Detail Page - add test

- tests/e2e/index.test.js
> minor fix to index.js tests

- source/assets/scripts/foodie.js
- source/assets/scripts/recipe-detail.js
- source/assets/styles/foodie.css
- source/assets/styles/recipe-detail.css
- source/foodie.html
- source/recipe-detail.html
**Do not merge until recipe-search branch is merged.**
> Add foodie mode logic

- source/assets/components/ExpandedRecipeCard.js
- source/assets/components/RecipeCard.js
- source/assets/scripts/backend.js
- source/assets/scripts/recipe-add.js
- source/assets/scripts/recipe-detail.js
- source/assets/scripts/recipe-searchPage.js
Addressed #111 
Added default keys and error checking so the recipes we add are valid
None
> added defaults and checks so things don't crash

- source/assets/styles/recipe-add.css
- source/recipe-add.html
Add Recipe Page Fix
- Modify difficulty mark position
- Modify checkbox position
- Modify bottom boxes (show index)
- Modify nav bar (font weight)
> Add Recipe Page Fix

- source/assets/styles/foodie.css
- source/foodie.html
Foodie Mode Page Fix
- Have a fixed height for nav (the title), as a model for fixing the title in other pages
- Add the dount design
- Change the background color (same as other pages)
- Modify the step wrapper (no need to slide up and down to view the step & click next/prev on mobile device)
- Fix the control wrapper at the bottom
> Foodie Mode Page Fix

- source/assets/styles/index.css
fixed custom recipe card not wrapping and zero margin
Added css to address that
None
> fixed custom recipe card display issue

- source/assets/styles/recipe-add.css
- source/recipe-add.html
1. update the cookingTime input box to let user know they should input the specific time
> update the cookingTime input box

- source/assets/components/RecipeCard.js
- source/assets/scripts/backend.js
- source/assets/scripts/recipe-add.js
- source/assets/scripts/recipe-data.js
> Fixed the saved recipe disappear problem and add page diffculty

- tests/e2e/recipe-detailE2E.test.js
- tests/e2e/settings.test.js
Added some tests for foodie mode and preference settings
> add tests: foodie mode and preference settings

- source/assets/scripts/recipe-detail.js
> fix back button in recipe-detail page

- source/assets/components/RecipeCard.js
- source/assets/styles/index.css
- source/assets/styles/onBoardingPage.css
made page look better
* shifted the buttons and size of the images manually in navbar to make them look even
* unified recipe card hover behavior
None
> tweaked the css on the index

- source/assets/scripts/backend.js
- source/assets/scripts/recipe-detail.js
- source/assets/scripts/recipe-searchPage.js
* added dynamic refresh based on the filter on the search page
* allowed the enter key to function as the search button
Created a global variable to store the fetched recipes and display a subset of the global recipes when the checkboxes are toggled.
Additionally, added the search function as an event listener for the enter key keyup event.
None
> Recipe search

- source/assets/components/RecipeCard.js
- source/assets/scripts/backend.js
- source/assets/scripts/recipe-add.js
- source/assets/scripts/recipe-detail.js
- source/assets/scripts/recipe-searchPage.js
- tests/e2e/foodie.test.js
- Implemented end-to-end tests for Foodie Mode to close #139 
> Add foodie mode E2E tests

- source/assets/scripts/foodie.js
- source/assets/scripts/index.js
- source/assets/scripts/onBoardingPage.js
- source/assets/scripts/preference-setting.js
- source/assets/scripts/recipe-add.js
- source/assets/scripts/recipe-detail.js
- source/assets/scripts/recipe-searchPage.js
- source/assets/scripts/setting.js
- source/assets/scripts/version.js
- source/assets/styles/onBoardingPage.css
Linked onboarding page
Added logic before each page load to redirect to onboarding if it is the first visit (determined by %not_first_visit flag in localstore)
> added logic to load the onboarding page and redirect

- source/assets/scripts/recipe-detail.js
- source/assets/styles/recipe-detail.css
Added checkboxes in recipe detail page
replaced the `<li>`s with `<div>`s and then added a checkbox and a span inside.
> added checkboxes for ingredients

- source/assets/components/ExpandedRecipeCard.js
- source/assets/styles/index.css
- source/assets/styles/recipe-add.css
- source/assets/styles/recipe-detail.css
- source/assets/styles/recipe-searchPage.css
- source/index.html
- source/recipe-add.html
- source/recipe-detail.html
- source/recipe-search.html
Final fix - expanded card & header
- Expanded Card
- delete the point element to not show the points of the recipe
- Header of the dashboard, add recipe page, search page, and recipe detail page
- Those pages may be scrolled down
- Fix the header so that the header is fixed at the top of the screen
> Final fix - expanded card & header

- specs/adrs/110521-data-models-in-a-recipe-component.md
- specs/adrs/110521-data-models-in-a-user-object.md
- specs/adrs/110521-settings-of-dietary-preferences.md
Adr files Modification
> Referred from Canvas:
> If you make one and undo the choice later on that should be noted in the document itself at the top and include when the change happened, a brief reason why the change was a made, and a link to any superseding decision document.
Make modifications to the ADR files recording:
- settings of dietary preferences
- data models in a user object
- data models in a recipe component
> ADR files Modification
